server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/acadyk_db}
    username: ${SPRING_DATASOURCE_USERNAME:acdayk}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  kafka:
    listener:
      auto-startup: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    clean-disabled: false

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.acadyk: INFO
    org.apache.kafka: ERROR
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
