// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7L6kNh3Noa1zFzoFcNm0i89Fe9WpmBg8',
    appId: '1:205477692906:web:1fd7598c3e49d56a4fde93',
    messagingSenderId: '205477692906',
    projectId: 'acadyk-54e1b',
    authDomain: 'acadyk-54e1b.firebaseapp.com',
    storageBucket: 'acadyk-54e1b.firebasestorage.app',
    measurementId: 'G-ZQRJ7TQ668',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEOKCZW1tYgendnKOGwpUj1uYqDP9Om_8',
    appId: '1:205477692906:android:ce5be2a07a23fe4d4fde93',
    messagingSenderId: '205477692906',
    projectId: 'acadyk-54e1b',
    storageBucket: 'acadyk-54e1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8t6AyPp_Vd7fSz4NgpmCYbticV29mXdY',
    appId: '1:205477692906:ios:4f47e0fbcd72457c4fde93',
    messagingSenderId: '205477692906',
    projectId: 'acadyk-54e1b',
    storageBucket: 'acadyk-54e1b.firebasestorage.app',
    iosClientId: '205477692906-02p40urisvoqg2qsndoregclohopkdgb.apps.googleusercontent.com',
    iosBundleId: 'com.acadyk.acadyk',
  );
}
