name: Flutter CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.11.x"
      - name: Install Dependencies
        run: cd apps/mobile && flutter pub get
      - name: Analyze
        run: cd apps/mobile && flutter analyze
      - name: Run Tests
        run: cd apps/mobile && flutter test
